#!/usr/bin/env bash
# Rebuild the Raly wasm module and drop it into playground/wasm/.
#
# Produces three files, all committed so the demo works from a fresh clone:
#
#   wasm/raly_wasm_bg.wasm         the module itself, for reference
#   wasm/raly_wasm.js              wasm-bindgen glue, --target no-modules
#   wasm/raly_wasm_embedded.js     the same module base64-encoded into a script
#
# The page loads the embedded copy rather than fetching the .wasm, which is
# what lets index.html work from a file:// URL with no server and no network.
#
# Usage:  bash playground/build.sh
set -euo pipefail

export PATH="$HOME/.cargo/bin:$PATH"

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root="$(cd "$here/.." && pwd)"
crate="$root/compiler/crates/raly-wasm"
out="$here/wasm"

step() { printf '\033[1m==>\033[0m %s\n' "$1"; }

step "Checking the toolchain"
command -v cargo >/dev/null || { echo "cargo not found; see playground/README.md" >&2; exit 1; }
rustup target list --installed | grep -qx wasm32-unknown-unknown \
  || rustup target add wasm32-unknown-unknown
command -v wasm-bindgen >/dev/null \
  || { echo "wasm-bindgen not found. Run: cargo install wasm-bindgen-cli --version 0.2.100" >&2; exit 1; }

step "Testing raly-wasm on the host"
(cd "$crate" && cargo test --quiet)

step "Building for wasm32-unknown-unknown"
(cd "$crate" && cargo build --release --target wasm32-unknown-unknown)

step "Running wasm-bindgen"
rm -rf "$out"
mkdir -p "$out"
wasm-bindgen \
  --target no-modules \
  --no-typescript \
  --out-dir "$out" \
  --out-name raly_wasm \
  "$crate/target/wasm32-unknown-unknown/release/raly_wasm.wasm"

step "Embedding the module as base64"
python - "$out/raly_wasm_bg.wasm" "$out/raly_wasm_embedded.js" <<'PY'
import base64, sys, io

src, dst = sys.argv[1], sys.argv[2]
payload = base64.b64encode(open(src, 'rb').read()).decode('ascii')

header = (
    "// Generated by playground/build.sh -- do not edit.\n"
    "// The raly-wasm module, base64-encoded, so index.html needs no fetch()\n"
    "// and therefore works from a file:// URL as well as from a static host.\n"
    "window.RALY_WASM_BASE64 = '"
)

# Wrap so the file stays diffable rather than one enormous line.
chunks = [payload[i:i + 120] for i in range(0, len(payload), 120)]
body = "'\n  + '".join(chunks)

with io.open(dst, 'w', encoding='utf-8', newline='\n') as f:
    f.write(header + body + "';\n")

print("  %d bytes wasm -> %d bytes base64" % (len(open(src, 'rb').read()), len(payload)))
PY

step "Done"
ls -l "$out"
echo
echo "Serve it with:  python -m http.server -d playground 8000"
echo "Or just open:   playground/index.html"
